[package]
name = "IDLE_Shit"
version = "0.1.0"
edition = "2021"

[dependencies]
native-windows-gui = "1.0.12"
native-windows-derive = "1.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.135"
chrono = "0.4.39"
bincode = "1.3"
rand = "0.8"
lazy_static = "1.5.0"
rfd = "0.15.2"